// js-react-styled/src/components/Counter.jsx
import styled from 'styled-components'

const Wrapper = styled.div`
  padding: 1rem;
`

const Button = styled.button`
  padding: 0.2rem 0.5rem;
  border-radius: 4px;
  background-color: blue;
  color: white;
  border: none;

  &.ml {
    margin-left: 0.5rem;
  }
`

function Counter() {
  const [count, setCount] = useState(1)
  const doubleCount = count * 2
  const increment = () => setCount((count) => count + 1)
  const decrement = () => setCount((count) => count - 1)
  return (
    <Wrapper>
      <p>count: {count}</p>
      <p>doubleCount: {doubleCount}</p>
      <Button onClick={increment}>+</Button>
      <Button className="ml" onClick={decrement}>
        -
      </Button>
    </Wrapper>
  )
}

export default Counter

// js-vue/src/components/Counter.vue
<script setup>
import { storeToRefs } from 'pinia'

const store = useDemoStore()
const { count, doubleCount } = storeToRefs(store)
const { increment, decrement } = store
</script>

<template>
  <div class="counter-wrapper">
    <p>
      <span>count: {{ count }}</span>
    </p>
    <p>
      <span>doubleCount: {{ doubleCount }}</span>
    </p>
    <button class="inc" @click="increment()">+</button>
    <button class="dec" @click="decrement()">-</button>
  </div>
</template>

<style lang="scss">
.counter-wrapper {
  padding: 1.25rem;

  .dec {
    margin-left: 1rem;
  }
}
</style>
