// ts-react-styled-mobx/src/components/Counter.tsx
import { observer } from 'mobx-react'
import styled from 'styled-components'
import { count } from '~/store/demo'

const Wrapper = styled.div`
  padding: 1rem;
`

const Button = styled.button`
  padding: 0.2rem 0.5rem;
  border-radius: 4px;
  background-color: blue;
  color: white;
  border: none;

  &.ml {
    margin-left: 0.5rem;
  }
`

function Counter() {
  const doubleCount = count.count * 2
  return (
    <Wrapper>
      <p>count: {count.count}</p>
      <p>doubleCount: {doubleCount}</p>
      <Button onClick={() => count.increment()}>+</Button>
      <Button className="ml" onClick={() => count.decrement()}>
        -
      </Button>
    </Wrapper>
  )
}

export default observer(Counter)

// ts-vue/src/components/Counter.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia'

const store = useDemoStore()
const { count, doubleCount } = storeToRefs(store)
const { increment, decrement } = store
</script>

<template>
  <div class="counter-wrapper">
    <p>
      <span>count: {{ count }}</span>
    </p>
    <p>
      <span>doubleCount: {{ doubleCount }}</span>
    </p>
    <button class="inc" @click="increment()">+</button>
    <button class="dec" @click="decrement()">-</button>
  </div>
</template>

<style lang="scss">
.counter-wrapper {
  padding: 1.25rem;

  .dec {
    margin-left: 1rem;
  }
}
</style>
