// js-vue-unocss/src/components/Counter.vue
<script setup>
import { storeToRefs } from 'pinia'

const store = useDemoStore()
const { count, doubleCount } = storeToRefs(store)
const { increment, decrement } = store
</script>

<template>
  <div class="p-4">
    <p>
      <span>count: {{ count }}</span>
    </p>
    <p>
      <span>doubleCount: {{ doubleCount }}</span>
    </p>
    <button class="inc btn" @click="increment()">+</button>
    <button class="dec btn ml-4" @click="decrement()">-</button>
  </div>
</template>

// js-react/src/components/Counter/index.jsx
import styles from './index.module.scss'

function Counter() {
  const [count, setCount] = useState(1)
  const doubleCount = count * 2
  const increment = () => setCount((count) => count + 1)
  const decrement = () => setCount((count) => count - 1)
  return (
    <div className={styles.wrapper}>
      <p>count: {count}</p>
      <p>doubleCount: {doubleCount}</p>
      <button className={styles.btn} onClick={increment}>
        +
      </button>
      <button className={`${styles.btn} ${styles.ml}`} onClick={decrement}>
        -
      </button>
    </div>
  )
}

export default Counter
